### ISSUE TITLE
Could you share the pretrained model ?

### ISSUE THREAD

**Issue by hoangnh2912** [ngockhanh5110/nlp-vietnamese-text-summarization#3]
Hello, I'm a student from Le Quy Don University, I have an assignment about running your source code and presenting text summarization.
When I build docker from source code, I get error ` > [6/9] RUN bash demo.sh:                                                                             
#10 1.670 BucketNotFoundException: 404 gs://kaggle-vbdi-test bucket does not exist.                    
#10 1.689 CommandException: 1 file/object could not be transferred.`, can you give me the pretrained model file. Thank you so much.

**Comment by ngockhanh5110** [comment]
Sorry mate,

I didn't maintain local versions of checkpoints. Can you start to retrain a new one? Then replacing some docker cmd would make `demo` run again.

FYI this repo is not well maintained and there is no plan for updating it in the future.
